version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/empathy-day
    overwrite: yes
permissions:
  - object: /home/ec2-user/empathy-day/
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user