spring:
  profiles:
    active : local
    include:
      - secret

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/empath_day?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: ${RDS_DB_URL}/${RDS_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}