spring:
  profiles:
    active : local
    include:
      - secret
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/empath_day?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 280993ef142836d3abb2bd75ca69421b
            client-secret: D5MUK7rnH5HsJdwIQjgP32Xq5JydkF4M
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth:
  jwt:
    secret: empath-day

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: ${RDS_DB_URL}/${RDS_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 280993ef142836d3abb2bd75ca69421b
            client-secret: D5MUK7rnH5HsJdwIQjgP32Xq5JydkF4M
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
              - birthday
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth:
  jwt:
    secret: empath-day

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true